# Generated by Django 5.1.2 on 2024-10-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
